FROM quay.io/natlibfi/skosmos:latest

USER root

RUN sed -i 's/^Listen 80$/Listen 8080/' /etc/apache2/ports.conf && \
    sed -i 's/<VirtualHost \*:80>/<VirtualHost *:8080>/' /etc/apache2/sites-available/000-default.conf && \
    sed -i 's/<VirtualHost \*:80>/<VirtualHost *:8080>/' /etc/apache2/sites-enabled/000-default.conf && \
    rm -f /etc/apache2/conf-enabled/other-vhosts-access-log.conf && \
    ln -sf /proc/self/fd/1 /var/log/apache2/access.log && \
    ln -sf /proc/self/fd/2 /var/log/apache2/error.log && \
    chmod -R g=u /var/log/apache2 /var/run/apache2 /var/lock/apache2 /var/www/html

EXPOSE 8080
